### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by ice1000** [cqjjjzr/BiliLiveLib#2]
```
java.lang.NullPointerException
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.getCommand(AbstractJSONDispatcher.java:52)
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.checkCanDispatch(AbstractJSONDispatcher.java:27)
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.tryDispatch(AbstractJSONDispatcher.java:45)
	at charlie.bililivelib.danmaku.dispatch.DispatchManager.dispatch(DispatchManager.java:44)
	at charlie.bililivelib.danmaku.DanmakuReceiver.dispatchPacket(DanmakuReceiver.java:166)
	at charlie.bililivelib.danmaku.DanmakuReceiver.run(DanmakuReceiver.java:148)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.NullPointerException
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.getCommand(AbstractJSONDispatcher.java:52)
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.checkCanDispatch(AbstractJSONDispatcher.java:27)
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.tryDispatch(AbstractJSONDispatcher.java:45)
	at charlie.bililivelib.danmaku.dispatch.DispatchManager.dispatch(DispatchManager.java:44)
	at charlie.bililivelib.danmaku.DanmakuReceiver.dispatchPacket(DanmakuReceiver.java:166)
	at charlie.bililivelib.danmaku.DanmakuReceiver.run(DanmakuReceiver.java:148)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.NullPointerException
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.getCommand(AbstractJSONDispatcher.java:52)
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.checkCanDispatch(AbstractJSONDispatcher.java:27)
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.tryDispatch(AbstractJSONDispatcher.java:45)
	at charlie.bililivelib.danmaku.dispatch.DispatchManager.dispatch(DispatchManager.java:44)
	at charlie.bililivelib.danmaku.DanmakuReceiver.dispatchPacket(DanmakuReceiver.java:166)
	at charlie.bililivelib.danmaku.DanmakuReceiver.run(DanmakuReceiver.java:148)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.NullPointerException
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.getCommand(AbstractJSONDispatcher.java:52)
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.checkCanDispatch(AbstractJSONDispatcher.java:27)
	at charlie.bililivelib.danmaku.dispatch.AbstractJSONDispatcher.tryDispatch(AbstractJSONDispatcher.java:45)
	at charlie.bililivelib.danmaku.dispatch.DispatchManager.dispatch(DispatchManager.java:44)
	at charlie.bililivelib.danmaku.DanmakuReceiver.dispatchPacket(DanmakuReceiver.java:166)
	at charlie.bililivelib.danmaku.DanmakuReceiver.run(DanmakuReceiver.java:148)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by cqjjjzr** [comment]
由于 Bilibili 弹幕协议更改，本项目目前已经停更。

请前往本人 WIP 中的 vNerve 项目。vNerve 项目通过消息队列实现了 Bilibili 协议无关的、更加稳定的 Bilibili 直播弹幕数据。

https://github.com/vNerve/vNerveBiLiveReceptor

**Comment by ice1000** [comment]
dl, sdl, awsl
